language: python
python: 2.7
sudo: false
cache:
- pip
env:
- TOXENV=py27-16
- TOXENV=py27-18
- TOXENV=pypy-16
- TOXENV=pypy-18
install:
- pip install tox
script:
- tox
deploy:
  provider: pypi
  user: ddanier
  password:
    secure: ""
  on:
    tags: true
    repo: team23/django_backend
    condition: "$TOXENV = py27-18"
