language: python
python: 2.7
sudo: false
cache:
- pip
env:
- TOXENV=py27-16
- TOXENV=py27-18
- TOXENV=pypy-16
- TOXENV=pypy-18
install:
- pip install tox
script:
- tox
deploy:
  provider: pypi
  user: ddanier
  password:
    secure: F+ybT9ui3MuMuf8ywMjbE4c3+3WgHyZ+LxRhgkSLdllBGY0En4XKAaUzKWn4g9u5Eq2UfK0RylvXgWujJ5D8AEYO101ASYImX++gGJqvF0NCHAiSmiuSAJusU80K/n+vcX0cBJB2ERiTWe1Ql0o/xqITsdz24NWmALc2f+I72wI=
  on:
    tags: true
    repo: team23/django_backend
    condition: "$TOXENV = py27-18"
